### ISSUE TITLE
404-555-1212 => 404--55-55-12

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#101]
Still have work to do since 404-555-1212 shows up as 404--55-55-12 in contact email.

**Comment by PepperTeasdale** [comment]
Should be fixed now... I was previously storing the number with 10 digits
only numeral characters and was using a presenter to format phone numbers.
Changed that with last update.

**Comment by jasnow** [comment]
looking at it now

**Comment by jasnow** [comment]
Verified
