### ISSUE TITLE
Google forms

### ISSUE THREAD

**Issue by PepperTeasdale** [SandersForPresident/BernieBNB#108]
Endpoint for "submit feedback" button will be a google form. Can be created here:
https://docs.google.com/forms/

Is there a Coders For Sanders organization that can have ownership of the form, or should we create a google group for Bernie BNB?

**Comment by jasnow** [comment]
REFs:
 * http://stackoverflow.com/questions/30331510/access-a-google-drive-spreadsheet-in-ruby-on-rails
 * https://github.com/gimite/google-spreadsheet-ruby
 * https://github.com/gimite/google-drive-ruby

**Comment by jasnow** [comment]
Use case: If a person logs in with Facebook credentials and clicks on 
"Submit Feedback", will they be asked for their Google credentials too.

**Comment by jasnow** [comment]
@PepperTeasdale - How do we test this feature?

**Comment by cmuld3r** [comment]
are we all on the same page about feedback? i think we should just create a google form and link in a new window. we can set the form to public so no login info is asked for. we can make a form similar to this one - http://bit.ly/rwb-feedback

i can create a copy of that one and modify it, if one doesn't already exist. is there already a google form created?

**Comment by PepperTeasdale** [comment]
https://docs.google.com/forms/d/1lH0VgWl1UTc6IG9-iFB1o9w3wgwcOYJxRdH7KKsgXCU/viewform

**Comment by jasnow** [comment]
One question from this morning's testing: Do we want the person to be able to click on both VIsitor and Host? (look for radiobutton, instead of checkboxes).

**Comment by PepperTeasdale** [comment]
Yes, because hypothetically they could have done both. I based this decision on the RWB form

**Comment by jasnow** [comment]
okay, just checking.

**Comment by cmuld3r** [comment]
is the button in? i suggested putting it on the host/travel index page, and possibly on the results page. here's a shortlink to the form if needed - http://bit.ly/berniebnb-feedback

**Comment by jasnow** [comment]
I was able to open the Google spreadsheet in read-mode

**Comment by jasnow** [comment]
What is the title on the "host/travel index page"s? We don't have index.html files for host or travel(visit).

**Comment by cmuld3r** [comment]
@jasnow i believe it's this one - https://github.com/SandersForPresident/BernieBNB/blob/master/app/views/users/show.html.haml

**Comment by jasnow** [comment]
@cmuld3r - Thanks

**Comment by PepperTeasdale** [comment]
My friend did not actually submit the google form, hence we didn't see his post. Others have since, so the form is confirmed to be working.
