### ISSUE TITLE
Add Tip Jar icon to README to help pay expenses.

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#113]
Add a  Tip Jar icon, such as https://gratipay.com, to README to help pay expenses.
Example: [tip_url]: https://www.gittip.com/deivid-rodriguez

**Comment by jasnow** [comment]
Going to use: [tip_url]: https://www.gittip.com/berniebnb
and hopefully this email (berniebnb@berniebnb.com) works.

**Comment by PepperTeasdale** [comment]
So setting up email with the domain registrar is a little complicated because we are using cloudflare's name servers. Can anyone recommend a good cheap/ free email forwarding service? As berniebnb@berniebnb.com does not work currently.

**Comment by jasnow** [comment]
@PepperTeasdale - Now you can use " berniebnbinfo@gmail.com" to register on https://www.gittip.com/berniebnbinfo or https://gratipay.com/berniebnbinfo web site.
