### ISSUE TITLE
Profile's empty phone number error handling is broken

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#115]
Empty phone number on Profile and click on "Send Email Confirmation" 
button on Staging gets "We're sorry, but something went wrong."

**Comment by fpcyan** [comment]
Is this taken care of? should this issue be closed?

**Comment by jasnow** [comment]
@fpcyan - Is this taken care of? - Not yet. See PR#119 for newer code, but stil [WIP]. @PepperTeasdale
