### ISSUE TITLE
Auto-deploy to bbnb-staging after green Travis build/run

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#118]
Propose auto-deploying to staging after green Travis build/run.

This would remove the manual step in testing pre-production/staging.

**Comment by jasnow** [comment]
PR #146 is part of the answer. Must check that failed runs are not deployed.

**Comment by jasnow** [comment]
REF for more work on this: http://stackoverflow.com/questions/27560551/head-detached-warning-in-travis-ci-when-deploying-to-heroku

**Comment by PepperTeasdale** [comment]
Okay, I have travis installed on my branch now. It is not deploying because travis.yml specifies your branch. Is this what you were talking about earlier @jasnow ?

**Comment by jasnow** [comment]
Yes, change the last line in .travis.yml to your repo name, 
SandersForPresident/BernieBNB or your personal Github account/BernieBNB.

**Comment by jasnow** [comment]
repo: 
    PepperTeasdale/BernieBNB

Also change:
    recipients:
    - jasnow@hotmail.com
to
   recipients:
   - berniebnbinfo@gmail

**Comment by jasnow** [comment]
probably need to change api_key when we change repo value.

**Comment by jasnow** [comment]
* Remove the whole section of "deploy:"
 * Run "gem install travis"
 * Run ' travis setup heroku"
 * Run 'cat .travis.yml" to see what changed.

**Comment by jasnow** [comment]
More info at: http://www.rotati.com/2015/01/basic-automated-deployment-from-travis-ci-to-heroku/

**Comment by PepperTeasdale** [comment]
Just had our first auto deploy
