### ISSUE TITLE
Incorrect ZIP error page creates error page without explanation

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#150]
From Feedback Spreadsheet row 20: "Whenever an incorrect ZIP is provided, 
it goes to an error page that does not specify the error, which could confuse some people."

**Comment by jasnow** [comment]
Unclear what "error page" above means, but I get a red flash message:
 * **Zipcode need to be 5 digits.**

**Comment by PepperTeasdale** [comment]
I wasn't able to reproduce either. I'm guessing they got rails' "something
went wrong" page. Looks like we need more test cases. Also does not specify
whether it was the visits or hosts page.

**Comment by jasnow** [comment]
More tests are good. Tried bother visits and hosts page. Got same errors either time.

**Comment by PepperTeasdale** [comment]
No one has been able to reproduce and we've not heard more feedback like this. Seperated into two concerns: #159 and #151
