### ISSUE TITLE
Facebook button on staging gets "App Not Setup" error

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#154]
**Facebook button on staging gets "App Not Setup" error**

Error message is: "App Not Setup: This app is still in development mode, 
and you don't have access to it. Switch to a registered test user or ask 
an app admin for permissions."

**Comment by PepperTeasdale** [comment]
I just fixed this. I am resetting the staging db so we don't have issues with email uniqueness validations.
Also, #156 changes action mailer settings so email confirmation will work on staging, too.
After this, staging *should* be working like prod.
