### ISSUE TITLE
Inconsistent "Cancel" color and position on page

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#155]
Sometimes "Cancel" button is above and white the non-cancel button and
sometimes "Cancel" button is below and red the non-cancel button.

Should they be consistent?

**Comment by PepperTeasdale** [comment]
The reason it's a different color when the user is persisted is they can delete and cancel on that page. I think we should actually have a small link somewhere on the page (probably around where it is now) to a different page for deleting the user profile, not just a button with an alert on the edit page. Thoughts?

**Comment by jasnow** [comment]
@cmuld3r - Any thoughts on this?

**Comment by jasnow** [comment]
With no other objectives, closing this issue.

**Comment by cmuld3r** [comment]
Sorry missed this. We could do the user profile cancel red and user profile delete white to keep it consistent, and reorder to save/cancel/delete. I think confirmation pop-up is good enough for delete. Think another page is necessary?

**Comment by cmuld3r** [comment]
Delete color isn't consistent, but it is a different kind of delete than the others.

**Comment by PepperTeasdale** [comment]
I don't think another page is necessary, but it is just what I've noticed on other websites. Perhaps it could be positioned differently. It is a very different kind of button than the others.

**Comment by cmuld3r** [comment]
Ok we all good with these proposed changes? user profile cancel red and user profile delete white to keep it consistent, and reorder to save/cancel/delete

**Comment by cmuld3r** [comment]
feel free to position how you feel appropriate
