### ISSUE TITLE
Confirmation email in staging going to BernieBNB url, not staging.

### ISSUE THREAD

**Issue by PepperTeasdale** [SandersForPresident/BernieBNB#157]
I think the reason why is the rails environment in staging is still set to prod. Looking into this now.

**Comment by PepperTeasdale** [comment]
Relevant: https://devcenter.heroku.com/articles/deploying-to-a-custom-rails-environment

**Comment by jasnow** [comment]
I would run " git config heroku.remote staging" on command line of 
your local repo and see what the variables are on staging server.
FYI: https://devcenter.heroku.com/articles/multiple-environments

**Comment by PepperTeasdale** [comment]
Fixed in #165
