### ISSUE TITLE
See if berniebnbinfo@gmail email can be forwarded into Github issues

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#158]
See if berniebnbinfo@gmail email can be forwarded into Github issues.

**Comment by jasnow** [comment]
Forward Gmail email into Github issue. 
 * https://zapier.com/zapbook/gmail/github/72/create-github-issue-email
 * https://zapier.com/zapbook/gmail/github/2970/create-github-issue-from-gmail
 * https://zapier.com/zapbook/github/gmail

* Create Github issue inside Gmail by adding a Gmail label
   * https://ifttt.com/recipes/210520-label-gmail-to-github-issue

**Comment by jasnow** [comment]
@PepperTeasdale - I think we don't need this currently.

**Comment by PepperTeasdale** [comment]
Agreed
