### ISSUE TITLE
EPIC: Add more error handling rspec tests.

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#159]
EPIC/GENERAL: Add more error handling rspec tests.

**Comment by jasnow** [comment]
To see the code that is not covered by tests in our test suite, run this:
 * **COVERAGE="true" rake**

Then open the results:
 * On OS/X, run **open coverage/index.html**
 * On Ubuntu, run **gnome-open coverage/index.html**

**Comment by PepperTeasdale** [comment]
Ah, that's very helpful! Will try to do some work toward this issue this weekend

**Comment by jasnow** [comment]
@PepperTeasdale - Great  - Ping me if you need me.

**Comment by PepperTeasdale** [comment]
I'm noticing that some parts of the code that *should* be getting hit by the tests are marked red in the coverage report. Others would be probably more trouble to test than their payoff. @jasnow was there any area in particular you felt needed extra coverage?

**Comment by jasnow** [comment]
Therefore "more trouble to test than their payoff" translates into let the users test them and tell us about the bugs.

"any areas" - I want no uncovered code but if I must answer then I would ask if you would identify all the methods with no coverage and focus on them. Example: The top one has one method with no coverage and one method with partial coverage.

**Comment by PepperTeasdale** [comment]
Fair enough. I understand your case for full test coverage. I will prioritize what we have no coverage on. Thank you.

**Comment by jasnow** [comment]
Sometimes you can delete the code because the condition can never be true "1 != 1" so you can't reach it.

**Comment by jasnow** [comment]
Pruning my old issues.
