### ISSUE TITLE
Create contacts

### ISSUE THREAD

**Issue by PepperTeasdale** [SandersForPresident/BernieBNB#16]
We will need a model for user contacts. The model will just have a host_id and visitor_id and respective associations and when created it will generate the email. It will have a dependent destroy on both associations.

**Comment by fpcyan** [comment]
I'm working on this. I didn't forget, I just fell asleep.

**Comment by PepperTeasdale** [comment]
Great! If you have a chance to make a PR so I can see what you have, I can also do some work on this.

**Comment by jasnow** [comment]
Found  "Send my contact info" button" (on visits/# web page)

**Comment by PepperTeasdale** [comment]
Fixed with: https://github.com/SandersForPresident/BernieBNB/pull/72
