### ISSUE TITLE
Add support for international phone numbers

### ISSUE THREAD

**Issue by PepperTeasdale** [SandersForPresident/BernieBNB#161]
A user who lives abroad and wants to travel to the states and campaign has requested support for international phone numbers. Ideally we can add this in the next few days.
Relevant: 
* https://github.com/sstephenson/global_phone
* https://github.com/floere/phony

We could also allow for an "international" option, wherein we skip any validation or formatting and rely on the user to provide something useful. I don't imagine this will get a ton of use, but the more people using the app, the better.

**Comment by jasnow** [comment]
I would recommend narrowing the focus to only support the needed subset of the international phone number that are currently wished for.

**Comment by jasnow** [comment]
Choices: https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers

**Comment by jasnow** [comment]
c.helman provided this format: "+46 XXX XXXXXX" so I have 
enhanced the model/specs to support "+DD XXX XXXXXX" which
is "+" char followed by 11 digits with special characters as before.
I will push it to Github and create a pull request shortly.
If you like the work, then accept it or add a comment to improve it.

**Comment by jasnow** [comment]
FYI: Storing international phone numbers like this: **+4655-512-3456**
"

**Comment by PepperTeasdale** [comment]
We are now supporting the requested phone format. We will add more if there is a big response.
