### ISSUE TITLE
Set up authentication with google

### ISSUE THREAD

**Issue by PepperTeasdale** [SandersForPresident/BernieBNB#17]

**Comment by jasnow** [comment]
Might be useful: https://github.com/zquestz/omniauth-google-oauth2

**Comment by jasnow** [comment]
Also: https://github.com/mohitjain/social-login-in-rails

**Comment by jasnow** [comment]
And: https://richonrails.com/articles/google-authentication-in-ruby-on-rails

**Comment by jasnow** [comment]
And: http://stackoverflow.com/questions/28129981/how-can-i-write-a-rails-4-test-for-creating-a-session-with-the-omniauth-google-o

**Comment by PepperTeasdale** [comment]
Google login is added, but no support for user using both services yet. New issue here: 
https://github.com/SandersForPresident/BernieBNB/issues/50
