### ISSUE TITLE
More phone validation problems

### ISSUE THREAD

**Issue by PepperTeasdale** [SandersForPresident/BernieBNB#170]
Intermittently getting "phone number too short" errors when running specs. I think this has something to do with the formats that Faker creates: 
https://github.com/stympy/faker#fakerphonenumber

All of these should be supported (we are using cellphone, so no extensions)

**Comment by jasnow** [comment]
Fixed

**Comment by jasnow** [comment]
Added fix as part of PR #171 .

**Comment by PepperTeasdale** [comment]
Closing for now. #172 will help us catch the error if it occurs again.
