### ISSUE TITLE
How to support if visit's start_date > app date

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#184]
How to support if visit's start_date > app date

I saw it last night (1/10/2016) around 10pm when the error message already talking about Jan.11, 2016.

**Comment by jasnow** [comment]
One way to deal with this issue is to change the validation from:
 * validates_date :start_date, on: :create, on_or_after: :today

To
 * validates_date :start_date, on: :create, presence: true  #on_or_after: :today

And remove the "is invalid with a start date in the past" rspec test.

What do you think?

**Comment by PepperTeasdale** [comment]
I suppose we can leave the validation off. The date picker (I believe) uses the client's timezone. Hopefully no one tries to time warp ;)

**Comment by PepperTeasdale** [comment]
Proposed changes merged with #183
