### ISSUE TITLE
`zipcode` to `zip_code`

### ISSUE THREAD

**Issue by PepperTeasdale** [SandersForPresident/BernieBNB#189]
When I started the project, I thought 'zip code' was one word. This doesn't effect the usability of the app in any way, but as more people contribute, the API should be correct and clear.

**Comment by jasnow** [comment]
Note that https://github.com/dgilperez/validates_zipcode gem want **zipcode not "zip_code".**

**Comment by PepperTeasdale** [comment]
I see. #198 is sufficient, then. Geocoder gem uses 'zip_code', but doesn't care what you call it.
