### ISSUE TITLE
Move incrementing of hostings.contact_counter to ContactsController#create

### ISSUE THREAD

**Issue by PepperTeasdale** [SandersForPresident/BernieBNB#190]
Currently we are incrementing that column in an after_create action in contact.rb, but this belongs on the controller. This involves rewriting some tests.

**Comment by PepperTeasdale** [comment]
@jasnow Made the necessary changes, but we need to rewrite some tests. We would like an extra set of eyes for best practices with rspec testing.

**Comment by jasnow** [comment]
Need to at least remove the "skip" in spec/features/create_visit_spec.rb file and fix associated tests.

**Comment by PepperTeasdale** [comment]
#216 "fixed" the broken specs. The specs themselves need improvement, and we have issues open for that.
