### ISSUE TITLE
Fix spec/models/visit_spec.rb tests

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#195]
Section 69 and 77.

The scenario is when the visit's start_date > app start_date, therefore the "visit" is tomorrow and the app is today. Example: West Coast is 10pm today and East Coast is 1pm tomorrow.

This might be useful: http://www.rubydoc.info/gems/time_zone_scheduler

**Comment by jasnow** [comment]
Interested comment from @jake3030 in #199: "Normally, when dealing with TZs, we save the timezone for the user in some column and save all dates and times in UTC and then change them on the frontend since TZ display is a view/presentation problem."

**Comment by jasnow** [comment]
Second @PepperTeasdale 's motion.

**Comment by PepperTeasdale** [comment]
Yes, I like that idea. I left a comment on #199 and opened #202

**Comment by jasnow** [comment]
#208 fixes this.
