### ISSUE TITLE
Improve README regarding Google/Facebook env vars.

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#200]
Improve README regarding Google/Facebook environment variables.
Found things (details) missing from README during WORK DAY.

**Comment by PepperTeasdale** [comment]
@jasnow Did #201 make the necessary changes or is it still lacking in details?

**Comment by cduffield** [comment]
Everything looked good in the README as far as setting up the facebook and google accounts as well as the commented out lines.

**Comment by jasnow** [comment]
Thanks @cduffield
