### ISSUE TITLE
Add Stats page: Implemented barebones mockup

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#203]
Implement barebones mockup : https://sites.google.com/site/bbmbbarebonesmockup/

**Comment by PepperTeasdale** [comment]
This ticket is for a very basic stats page, per this mockup:
https://sites.google.com/site/bbmbbarebonesmockup/

**Comment by jasnow** [comment]
I was expecting the stats page to start with the barebones mockup and end with the original mockup page, but let's get to barebones 1st.

**Comment by PepperTeasdale** [comment]
Oh, I understand, so, the end goal is actually more like:
https://sites.google.com/site/berniebnbinfowiki/home/bbnb-stats-page-mockup

The BarebonesMockup should be up soon.

**Comment by jasnow** [comment]
Checked out #224 locally, on staging, and in production. (looks good).

Moving original mockup work to another issue
