### ISSUE TITLE
Missing error handling for malformed URLs

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#229]
Missing error handling for malformed URLs:
 * http://bbnb-staging.herokuapp.com/users (Note no user number at the end)
 * http://bbnb-staging.herokuapp.com/users/visits/new (No user number after "/users/")
 * http://bbnb-staging.herokuapp.com/users/16/visits/ (No visits number at the end)

**Comment by PepperTeasdale** [comment]
I will do work on this tomorrow. For one, we have a bunch of unused routes defined. I will start cleaning up routes.rb and go from there.

**Comment by PepperTeasdale** [comment]
@jasnow did #234 take care of this issue or is there something else that you are pointing out here?

**Comment by jasnow** [comment]
Think we need excecption handling on redirects.

 * Now when I do this:
   * http://bbnb-staging.herokuapp.com/users/
     * I get [No route matches [GET] "/users"]
   * http://bbnb-staging.herokuapp.com/users/visits/new
     * I get [No route matches [GET] "/users/visits/new"]
   * http://bbnb-staging.herokuapp.com/users/16/visits
     * I get [No route matches [GET] "/users/81/visits"]

**Comment by jasnow** [comment]
Verified in staging.
