### ISSUE TITLE
Improve calendar

### ISSUE THREAD

**Issue by PepperTeasdale** [SandersForPresident/BernieBNB#265]
Make the date selector for visits more clear. It should be obvious that the volunteer is to put start and end dates on that calendar. Ways to accomplish this:
* Color coding start and end dates
* More clear instructions in label text
* Text at bottom saying which dates are currently selected
* Mouseover text

We should do at least one of these and potentially all of them.

**Comment by cockroachbill** [comment]
![screen shot 2016-02-20 at 5 51 42 pm](https://cloud.githubusercontent.com/assets/393907/13199935/ae8a78a8-d7fa-11e5-884a-7eb6eb3985ca.png)

**Comment by cockroachbill** [comment]
Has this been addressed sufficiently enough to close the issue?

**Comment by jasnow** [comment]
@PepperTeasdale - What's the status of this issue?
