### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by PepperTeasdale** [SandersForPresident/BernieBNB#266]
If we are simplifying instructions on the landing page, we can give more detailed instructions here. We can also use this page to answer common questions from emails/ user feedback form. buddhistsforbernie is working on the copy for this, and I will proofread/ edit as necessary.

**Comment by PepperTeasdale** [comment]
https://github.com/SandersForPresident/BernieBNB/wiki/FAQ

**Comment by jasnow** [comment]
Are you going to link this inside the app?

**Comment by PepperTeasdale** [comment]
We are going to put the FAQ in the app. The wiki is just for collaborative editing and proofreading

**Comment by jasnow** [comment]
ok

**Comment by jasnow** [comment]
Proofread [FAQ](https://github.com/SandersForPresident/BernieBNB/wiki/FAQ) and add my changes. Have several remaining questions:
     -1- 1st answer: Do we need to say "out-of-state" each time it is used?
     -2- 6th answer: Unclear about how "blackout dates" are implemented for hosts?
     -3- 7th answer: MISSING

**Comment by PepperTeasdale** [comment]
Thanks, I just updated per your notes.

**Comment by jasnow** [comment]
@cockroachbill - What's the status of this issue?
