### ISSUE TITLE
Research pros and cons for Bulk Mailers

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#313]
**Research pros and cons for Bulk Mailers**

Initial Research
  * http://blog.meldium.com/home/2013/4/22/dont-spam-your-users-batch-notifications-in-rails
  * http://www.coldandheartless.com/blog/2013/09/mass-mailing-in-rails
  * delay_job gem - https://github.com/collectiveidea/delayed_job
  * Mailgun - https://github.com/jorgemanrubia/mailgun_rails
  * Sendgrid - http://stackoverflow.com/questions/7825465/best-practices-for-sending-email-to-lots-of-recipients-rails-sendgrid
  * Mailchimp - http://aspiringwebdev.com/e-mail-in-rails-with-mailchimp-and-mandrill-a-comprehensive-guide

**Comment by jasnow** [comment]
More Pros/Cons
 * http://stackshare.io/stackups/mailgun-vs-mandrill-vs-sendgrid
 * 2 years ago: https://www.ventureharbour.com/transactional-email-service-best-mandrill-vs-sendgrid-vs-mailjet
   * Their favorites SendinBlue, SendGrid
      * https://www.sendinblue.com (9k/month free)

**Comment by jasnow** [comment]
Mandrill vs Mailchmp: http://blog.mailchimp.com/important-changes-to-mandrill

**Comment by jasnow** [comment]
@PepperTeasdale - Are we done with this?

**Comment by PepperTeasdale** [comment]
Thanks for the research, @jasnow
