### ISSUE TITLE
New email strategy

### ISSUE THREAD

**Issue by PepperTeasdale** [SandersForPresident/BernieBNB#314]
Hosts and visitors are getting overwhelmed with emails and marking our emails as spam, resulting in users who do want emails not always receiving them. Per our meeting on 5/21, we have decided to change our email strategy. Currently, a visitor is notified every time a host signs up where they are looking and a host is emailed every time a visitor contacts them.

The new strategy is to create an email digest that emails visitors once a day with a list of new hosts in their area. Likewise, all contacts will be sent to the hosts in one daily email. The first pass will be an 'ugly' simple email, then Clarissa will design some more attractive emails for us to send out. We will also email all active users about the new changes.

**Comment by jasnow** [comment]
#327 will be used for Clarrissa's more attractive email work

**Comment by jasnow** [comment]
#327 and #332 covers above loose ends and future issues will 
be tracked separately therefore this is done and will be closed.
