### ISSUE TITLE
Ran out of good Sendgrid credits

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#318]
May 25: Received this by email: Not getting confirmation emails/Not able to sign up
```
I'm getting multiple emails from potential People's Summit attendees 
telling me that they are not getting confirmation emails / aren't able to
sign up. I've also tried myself and have not been successful.
Can you let me know when issue is resolved? If it's not or can't be, 
we need to make sure we're not directing people to the site for help
with housing up to and during the Summit.
```

**Comment by clarissa1287** [comment]
From Justin: "Looks like we ran out of good credit with the email provider. I have put a message on the front page saying that the service is temporarily down. I have made some progress on the email fix, but need to finish over the next couple of days, so we will be down for a bit while that happens. Anyway, this is my top priority while I'm not at work. Shouldn't be much longer."

**Comment by jasnow** [comment]
Just talked to People's Summit lady and now she understands the issue.
Also submitted a PR against Justin's PR to fix 2 tests.

**Comment by PepperTeasdale** [comment]
@jasnow Can we close this, or should we wait until it's in production?

**Comment by jasnow** [comment]
After we announce it.

**Comment by jasnow** [comment]
Believe this issue has service its purpose, will create separate issues for new thing we find now that will are in soft/beta release therefore I'm going to close this issue.
