### ISSUE TITLE
Please add me to Staging's Facebook stuff

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#320]
When I do "https://bbnb-staging.herokuapp.com" and click on Facebook button to log in, I get:
```
Can't Load URL: The domain of this URL isn't included in the app's 
domains. To be able to load this URL, add all domains and subdomains 
of your app to the App Domains field in your app settings.
```
When I click on Google button, I am logged in as: https://bbnb-staging.herokuapp.com/users/16

**Comment by jasnow** [comment]
http://stackoverflow.com/questions/37063685/facebook-oauth-the-domain-of-this-url-isnt-included-in-the-apps-domain

**Comment by PepperTeasdale** [comment]
Are you still unable @jasnow ?

**Comment by jasnow** [comment]
now it works

**Comment by jasnow** [comment]
Reappears so reopened issue.

**Comment by PepperTeasdale** [comment]
Staging is now only accessible through http://www-staging.berniebnb.com
