### ISSUE TITLE
Add more words on Feedback form so folks clearly understand that this feedback is anonymous

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#343]
Add more words on Feedback form so folks clearly understand that this feedback is anonymous.

**Comment by PepperTeasdale** [comment]
I made the header indicate *Anonymous* Feedback Form and added the copy that we are unable to respond to their requests unless they email us directly. Please close if you are satisfied or offer advice to improve further.

**Comment by jasnow** [comment]
Can you add "Anonymously" to the right of the submit button?

**Comment by jasnow** [comment]
Tried feedback form and I'm happy with it now.
