### ISSUE TITLE
Provide button under Delete Host to show list of current contacts

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#352]
Unclear how to check to see what the current contacts 
are so provide a way to see list of current contacts.

Also include a "RESEND" button to query an old contact up again.

**Comment by PepperTeasdale** [comment]
This would be a good improvement I think. This could be included in the hosting 'show' page. Below the button to delete the hosting record on the edit page, we could have a link to 'see all contacts'.

**Comment by jasnow** [comment]
@PepperTeasdale - Agree with your previous comment.

**Comment by PepperTeasdale** [comment]
@jasnow this seems related to #355 Could we close that and use this as the answer to that open question?

**Comment by jasnow** [comment]
This is a long term solution where #355 is a catch-up. We can close #355 if we are not going to do anything with existing stuff.

**Comment by jasnow** [comment]
Pruning my old issues.
