### ISSUE TITLE
Question: What is the longest contact/hosts list in our emails that we support?

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#354]
Question: What is the longest contact/hosts list in our emails that we support?

**Comment by PepperTeasdale** [comment]
No limit currently. Do you recommend one?

**Comment by jasnow** [comment]
worried about surprises for VERY LONG list of emails

**Comment by PepperTeasdale** [comment]
Unless we get EXTREMELY popular it shouldn't be a problem. Mailgun notifies us of dropped emails if that's your concern

**Comment by PepperTeasdale** [comment]
Per our conversation off github, closing

**Comment by jasnow** [comment]
Closing this for now - Will reopen if problem appears.
