### ISSUE TITLE
Are we going to requery all existing contacts as part of 2.0 release?

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#355]
Are we going to requery all existing contacts as part of 2.0 release?

**Comment by PepperTeasdale** [comment]
When you say 'requery' do you mean send a new email? I think you're referring to people who contacted someone previously but when our emails were down they never got emails. Correct?

**Comment by jasnow** [comment]
The question is do we do anything with previous contacts?

**Comment by jasnow** [comment]
too much email
