### ISSUE TITLE
Which timezone to use in Contacts email?

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#356]
Tonight's email had on line one: **our offer today, June 04, 2016:** - WRONG date or timezone.

**Comment by jasnow** [comment]
Change "Date.today" to "Time.zone.today" - Reference: http://danilenko.org/2012/7/6/rails_timezones

**Comment by jasnow** [comment]
Time.zone is currently UTC

**Comment by PepperTeasdale** [comment]
What timezone would you recommend for the date? I think since we send the notifications out in the early evening east coast time, EST should cover all of our US-based users

**Comment by jasnow** [comment]
I suggest we just removed the specific date and stop the sentence with "our offer today".

**Comment by jasnow** [comment]
#358 - setting to 'UTC' works (rake is green) but setting to "EST' breaks "rake" run (11 failed tests).

**Comment by jasnow** [comment]
Pruning my old issues.
