### ISSUE TITLE
Match the design

### ISSUE THREAD

**Issue by cmuld3r** [SandersForPresident/BernieBNB#36]
design is here - https://www.figma.com/file/HA4EjGlfqdZz5E5DEAqPSS/Bernie-BNB-v4 (login with slack)

and we can use RideWithBernie as a guide for the styles, classes and such, as they share the same design template - https://github.com/SandersForPresident/RideWithBernie/tree/master/app/assets/javascripts/templates https://github.com/SandersForPresident/RideWithBernie/tree/master/app/assets/stylesheets

**Comment by cmuld3r** [comment]
i started with the home page here in rwb_styles branch - https://github.com/SandersForPresident/BernieBNB/blob/rwb_styles/app/views/home/sign_in.html.erb

but that was before we moved to haml

**Comment by cmuld3r** [comment]
which pages are remaining?

**Comment by cmuld3r** [comment]
looks like there are still some pages to be re-done with bootstrap styles (similar to rwb code). @drsloth are you working on anything right now and what pages are left?

**Comment by PepperTeasdale** [comment]
I think his latest PR styles the results page with Berniestrap styles. But
I don't have my laptop with me to check it out.

**Comment by cmuld3r** [comment]
Ok I just peeked at heroku, I will pull up the latest.

**Comment by PepperTeasdale** [comment]
Ok, the latest changes to the styling should have us matching the design. I put it on heroku, please confirm.

**Comment by PepperTeasdale** [comment]
@cmuld3r How does it look now? Any last things to change or should we close this issue? Or we can make new issues for any more specific differences.

**Comment by PepperTeasdale** [comment]
Closing, since I have put your feedback on the current design into seperate issues @cmuld3r
