### ISSUE TITLE
Email validation fails if you choose to omit your email at facebook auth

### ISSUE THREAD

**Issue by drsloth** [SandersForPresident/BernieBNB#38]

**Comment by jasnow** [comment]
Can you please give me the steps to follow? I ran "rails server" locally and another browser (without Lasspass running) and I get Facebook Login/Password page but I get error message if I click done before I fill in login and password. Thanks.

**Comment by drsloth** [comment]
Before you fill in the first name and phone number fields, when you first authenticate through Facebook you can elect not to provide your email address. 

Go to Facebook and revoke the app permissions in App Settings and clear the existing record from the DB, then go back to sign up through the Facebook login option and click Edit the info you provide. If you uncheck the email address and then click okay, you'll end up with: Validation failed: Email can't be blank, Email is invalid
