### ISSUE TITLE
Repo needs license file

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#4]
Repo needs license file, such as MIT, Apache, BSD. More info/choices at: https://opensource.org/licenses

Example: https://github.com/SandersForPresident/ArborApp/blob/develop/LICENSE.txt

**Comment by PepperTeasdale** [comment]
I think we can just use the same license as the example . Does anyone have any thoughts to the contrary?

**Comment by jasnow** [comment]
@PepperTeasdale - Does the organization (higher uppers) have any policy/etc?

**Comment by PepperTeasdale** [comment]
@cmuld3r might know that

**Comment by cmuld3r** [comment]
i don't think there is a policy as coders for sanders isn't officially related to the campaign. GNU Affero is fine.
