### ISSUE TITLE
Submit Feedback Button

### ISSUE THREAD

**Issue by PepperTeasdale** [SandersForPresident/BernieBNB#43]
Is this a link to a form or to send an email? Who should receive the feedback?

**Comment by jasnow** [comment]
You can see it on the visit/# web page.

**Comment by jasnow** [comment]
Shortly will submit initial code on this feature. Based on this: https://matharvard.ca/posts/2014/jan/11/contact-form-in-rails-4

TODOs:
 * Link to "Submit Feedback" button.
 * Add styling (css)/etc.

To see the feature, log in using app and then change URL in browser to https://localhost:3000/feedback .

**Comment by jasnow** [comment]
Initial code in PR #87

**Comment by cmuld3r** [comment]
in rwb, we linked to a google form which has been effective - bit.ly/rwb-feedback

i'd suggest the same

**Comment by PepperTeasdale** [comment]
Moved to #108
