### ISSUE TITLE
Allow for multiple omniauth providers

### ISSUE THREAD

**Issue by PepperTeasdale** [SandersForPresident/BernieBNB#50]
Right now omniauth creates two different accounts for google and facebook, which causes problems with email uniqueness constraints. Should just add provider if user with that email already exists.

**Comment by jasnow** [comment]
@PepperTeasdale 
```
app/controllers/sessions_controller.rb:  User.create_with_omniauth(auth)
app/models/user.rb:                      def self.create_with_omniauth(auth)
```
See if we need both create_with_omniauth's.

**Comment by jasnow** [comment]
References:
 * https://github.com/intridea/omniauth/wiki/Managing-Multiple-Providers
 * http://axonflux.com/omniauth-10-how-to-do-googletwitterfacebook-l

**Comment by jasnow** [comment]
@PepperTeasdale - Is this still true?

**Comment by PepperTeasdale** [comment]
I looked into the above references, and I'm not so sure we want to do this anymore. It might be overkill for a small app like this and likely most users would never take advantage of this. The primary advantage would be that if someone signs up with google and later accidentally signs up with facebook, they will have access to the same data.

**Comment by jasnow** [comment]
Okay

**Comment by PepperTeasdale** [comment]
However, if we do get feedback that users want to be able to sign up without using Facebook or google, we can later implement the Identity strategy, so it's good to know about these options.

**Comment by jasnow** [comment]
OK
