### ISSUE TITLE
Merge database.yml and database.yml.travis files.

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#52]
Merge database.yml and database.yml.travis files.

**Comment by PepperTeasdale** [comment]
@jasnow I'm still not sure how the set up for Travis works. How specifically should I be merging them?

**Comment by jasnow** [comment]
This is okay as-is for now. Will close and reopen if I find someone to help out with database configs.

**Comment by jasnow** [comment]
PR #76 fixes this issue.

**Comment by jasnow** [comment]
Verified. Evidence: https://travis-ci.org/jasnow/BernieBNB/builds/99748520
