### ISSUE TITLE
Only admins and current user should have edit access

### ISSUE THREAD

**Issue by fpcyan** [SandersForPresident/BernieBNB#60]
The current implementation of the controllers allows anybody to add, delete, or edit anything by simply sending up whatever values they want for the parameters.

The controllers should only allow access to methods by appropriate parties. e.g. Only the current user may edit/delete her profile. Only the current user may add visits or host listings in her name. 

I don't think this is the case currently, and represents a relatively open doorway for abuse.

**Comment by PepperTeasdale** [comment]
Have you been able to do this?
There is a `require_current_user` callback in the application controller. Perhaps it is missing some edge cases?

**Comment by fpcyan** [comment]
I thought that only disallows navigation? Does it control who can send a
valid post to the server?

Still, creation of new objects should be through current_user associations
when possible so someone who is logged in can't spoof params to edit data
not tied to their account. No?

**Comment by PepperTeasdale** [comment]
It is a callback for all controller actions unless there is a skip_before_action. But, yeah, I think we can user the current_user helper method in some cases.

**Comment by fpcyan** [comment]
Ahh, right. So it does exclude someone who is not signed in from accessing controller methods, but in the cases of the following, any signed in user can mess with it (I believe):
* VisitsController - show, edit, update, destroy
* HostingsController - edit, update, destroy

Everything else either uses the current_user id to do the work or acts only on the current_user's data.
