### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by cmuld3r** [SandersForPresident/BernieBNB#8]
Let's review the email notifications and their content. I'd suggest plaintext for now. Based on the v4 design (https://www.figma.com/file/HA4EjGlfqdZz5E5DEAqPSS/Bernie-BNB-v4):

Signup email
```
Subject: BernieBNB: Thanks for signing up!

Hi {first_name},

Thanks for signing up with BernieBNB!

You can add, edit or delete your travel/host requests anytime here: {profile_link}
```

Legal disclaimer 
```
Legal Disclaimer: By agreeing to use this service, you hereby agree to waive any and all claims arising from your use of this service against the Bernie Sanders campaign, any groups associated with the Bernie Sanders campaign, and Coders for Sanders.
```
- Where should this go?

Email to nearby travelers (within 25 mi.) when a new host record is created
```
Subject: BernieBNB: New host in the area!

Hi {first_name},

{host_first_name} just signed up with BernieBNB as a host {distance} mi. from {zip}.

Send your contact info here: {results_link}
```

Email to host, when contacted
```
Reply-to: {host_email}
Subject: BernieBNB: You've been contacted by {traveler_first_name}

Hi {first_name},

You’ve been contacted by a traveler!

{traveler_first_name}
{traveler_phone}
{traveler_email}
{traveler_arrival_date} - {traveler_departure_date}
Group of {total_travelers}

Reply to this email, or contact {traveler_first_name} at {traveler_phone} for more details!

You can add, edit or delete your host offers anytime here: {profile_link}
```

**Comment by jasnow** [comment]
Refrence: http://guides.rubyonrails.org/action_mailer_basics.html

**Comment by PepperTeasdale** [comment]
I have the templates made here: https://github.com/SandersForPresident/BernieBNB/tree/master/app/views/user_mailer

**Comment by jasnow** [comment]
NOTE: We do not have the person's name when we send the Signup/Welcome email. FYI.

**Comment by jasnow** [comment]
FYI: letter_opener only works with "rails server" and only the first time the user logs in.

**Comment by PepperTeasdale** [comment]
I think we should move the disclaimer to the confirmation email now that we're doing that.

**Comment by jasnow** [comment]
@PepperTeasdale - If you "move the disclaimer", then please change the description of this ticket to document this change.

**Comment by jasnow** [comment]
@PepperTeasdale - What's the status of this ticket? If partial done, I suggest breaking it up into done and not-done parts.

**Comment by jasnow** [comment]
Verified that above 3 template have been implemented.
