### ISSUE TITLE
Propose coloring the "Send my contact info" link on Visits page

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#83]
Question: Should we colorize the "Send my contact info" link on Visits page?

**Comment by cmuld3r** [comment]
looks like the whole contact page needs to be styled with bootstrap. i can take a look later at some remaining pages.

**Comment by PepperTeasdale** [comment]
I believe this has been resolved, please confirm

**Comment by jasnow** [comment]
Verified
