### ISSUE TITLE
zip code validation?

### ISSUE THREAD

**Issue by cmuld3r** [SandersForPresident/BernieBNB#89]
I put in a 4 digit zip - '9131' and it was accepted. I think that's an international zip. Are we validating the zip for 5 digits, or any other validation?

**Comment by jasnow** [comment]
Maybe use: https://github.com/dgilperez/validates_zipcode

**Comment by jasnow** [comment]
@cmuld3r:
 * First, to answer your question - we currently only check that we have some value.
 * Second, Can I limit the zip code to US zip codes?

**Comment by jasnow** [comment]
Ready to push validation code to Github.

**Comment by jasnow** [comment]
@cmuld3r - Please try out the new version of the app and see if it is fixed.

**Comment by PepperTeasdale** [comment]
Currently only accepts 6-digit zipcodes. I think that's alright, but the message only says "Invalid zipcode", should mention it must be 6-digits.

**Comment by jasnow** [comment]
I thought zip code were 5-digits (30075) or 9+1 (30076-3515).

**Comment by PepperTeasdale** [comment]
That what I meant, apologies

**Comment by jasnow** [comment]
Adding more tests. Now error message will be: **Zipcode need to be 5 digits.**

**Comment by jasnow** [comment]
FYI: Currently not supporting 9+1 zip codes.

**Comment by jasnow** [comment]
@PepperTeasdale and @cmuld3r  - Anything else?

**Comment by PepperTeasdale** [comment]
I think that should cover it.
