### ISSUE TITLE
Matching own user's records

### ISSUE THREAD

**Issue by cmuld3r** [SandersForPresident/BernieBNB#90]
If a user has a host and travel record which match (within range), the user sees their own host record when they try to contact hosts and gets the email that a new host signed up. We should exclude these.

**Comment by drsloth** [comment]
I have a PR open to fix this. We're going to integrate it a bit later

**Comment by PepperTeasdale** [comment]
It's kind of helpful to be able to see your own hostings when you are testing the app on rails server, though I understand why this is undesirable behavior.

**Comment by jasnow** [comment]
@drsloth - Is it possible for your PR to only work in production?

**Comment by drsloth** [comment]
@jasnow Not sure I'll think on it. For now I think we can just leave it open until we want to merge it in

**Comment by PepperTeasdale** [comment]
I changed it so it's only on production and also use the same logic when sending emails notififying visitors of new hosts. Fixed in #105
