### ISSUE TITLE
Contact email tweaks

### ISSUE THREAD

**Issue by cmuld3r** [SandersForPresident/BernieBNB#91]
My phone number is wrong in the contact email - it duplicated the sixth digit and i ended up with an 11 digit number. ex. 123-456-7890 was shown as 123-456-67890

Also, can we set the reply-to to the host email?

**Comment by jasnow** [comment]
@cmuld3r - Please check out the app and verify/close this issue if it is done. Thanks.

**Comment by PepperTeasdale** [comment]
If the user adds dashes or other characters, the phone number validation fails now. #92 took away the regex to strip those, perhaps we should add it back?

**Comment by jasnow** [comment]
Define supported "other characters".

**Comment by PepperTeasdale** [comment]
Hyphens, parentheses, periods.

**Comment by jasnow** [comment]
Here are 6 examples I going to add to the tests and then change the code:
```
404-555-1212
1-404-555-1212
(404)555-1212
(404) 555-1212
404.555-1212
1.404.555.1212
```
**Any more?**

**Comment by jasnow** [comment]
Note I added blank after parentheses example too.

**Comment by PepperTeasdale** [comment]
Should be sufficient

On Sat, Jan 2, 2016 at 2:08 PM, Al Snow <notifications@github.com> wrote:

> Note I added blank after parentheses example too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SandersForPresident/BernieBNB/issues/91#issuecomment-168417440>
> .
>



-- 
Justin Schulz
Web Developer

T: 314-269-6223
E: justin.schulz@gmail.com
http://www.justinschulz.me/

**Comment by jasnow** [comment]
If we figure out more types, we can add them as tests and fix the code.
