### ISSUE TITLE
Click on "Bernie BNB Profile" in contact email resulted in error page

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BernieBNB#93]
Clicking on  "Bernie BNB Profile" resulted in error page.

Step to reproduce:
 1. Log in and create a host and a visit with same zip code.
 2. Given you are on "http://localhost:3000/visits/1" page and you click on "Contact" button and then "Send my contact info" link, you get an email.
 3. When you click on the "Bernie BNB Profile" link in the contact email, you get "No route matches [GET] "/hostings/1" error page.
 4. Therefore "hosting_url(@host)" is not defined in files:
   * app/views/user_mailer/contact_host_email.html.erb
   * app/views/user_mailer/contact_host_email.text.erb

**Comment by PepperTeasdale** [comment]
There is no view/ controller for hosting_url, should be edit_hosting_url. Will fix.
